module.exports = {
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts'],
  coveragePathIgnorePatterns: [
    'constants',
    'keys',
    'mock/*',
    'src/config',
    'src/api',
    'src/index.tsx',
    'src/config',
    'src/core/Routing/Routing.tsx',
    'src/core/Routing/constants',
    'src/core/Routing/guards',
    'src/library',
    'src/hooks/useScrollLock/constants.ts',
    'src/store/configureStore.ts',
    'src/store/reducers.ts',
    'src/store/store.ts',
    'src/store/watchers.ts',
    'src/tests',
    'src/translations',
    'src/types',
    'src/utils/history',
  ],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  modulePaths: [],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|svg|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/svgrMock.js',
    '\\.(css|scss)$': 'identity-obj-proxy',
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
  },
  resetMocks: true,
  roots: ['<rootDir>/src'],
  setupFiles: ['react-app-polyfill/jsdom'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  testEnvironment: 'jsdom',
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
    '<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}',
  ],
  testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
};
