export const REDUCER_KEY = 'pageBuilder';

export const ADD_ELEMENT = `${REDUCER_KEY}/ADD_ELEMENT`;

export const ADD_SELECTED_ELEMENT = `${REDUCER_KEY}/ADD_SELECTED_ELEMENT`;
export const REMOVE_SELECTED_ELEMENT = `${REDUCER_KEY}/REMOVE_SELECTED_ELEMENT`;
export const SET_SELECTED_ELEMENTS = `${REDUCER_KEY}/SET_SELECTED_ELEMENTS`;
