export enum E2EAttribute {
  anchor = 'anchor',
  box = 'box',
  button = 'button',
  buttonIcon = 'button-icon',
  colorPicker = 'color-picker',
  fieldGroup = 'field-group',
  form = 'form',
  icon = 'icon',
  logo = 'logo',
  resize = 'resize',
  section = 'section',
  tab = 'tab',
  test1 = 'test1',
  test2 = 'test2',
  text = 'text',
  textField = 'text-field',
  unset = 'unset',
}
