export enum Spacing {
  'm' = 'margin',
  'mb' = 'margin-bottom',
  'ml' = 'margin-left',
  'mr' = 'margin-right',
  'mt' = 'margin-top',
  'mx' = `margin-left;margin-right`,
  'my' = 'margin-top;margin-bottom',
  'p' = 'padding',
  'pb' = 'padding-bottom',
  'pl' = 'paddng-left',
  'pr' = 'padding-right',
  'pt' = 'padding-top',
  'px' = 'padding-left;padding-right',
  'py' = 'padding-top;padding-bottom',
}
